# Generated by Django 5.2.7 on 2025-11-04 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("direccion", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("encargado", models.CharField(max_length=100)),
                ("correo_encargado", models.EmailField(max_length=254)),
                (
                    "direccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="direccion.direccion",
                    ),
                ),
            ],
        ),
    ]
