# Generated by Django 5.2.4 on 2025-11-01 04:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='fecha_asignacion_cuadrilla',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario_valida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_validadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seguimientosolicitud',
            name='estado_anterior',
            field=models.CharField(choices=[('creada', 'Creada por Territorial'), ('derivada', 'Derivada a Departamento'), ('asignada', 'Asignada a Cuadrilla'), ('en_proceso', 'En Proceso por Cuadrilla'), ('finalizada', 'Finalizada por Cuadrilla'), ('validada', 'Validada por Territorial'), ('rechazada', 'Rechazada por Territorial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='seguimientosolicitud',
            name='estado_nuevo',
            field=models.CharField(choices=[('creada', 'Creada por Territorial'), ('derivada', 'Derivada a Departamento'), ('asignada', 'Asignada a Cuadrilla'), ('en_proceso', 'En Proceso por Cuadrilla'), ('finalizada', 'Finalizada por Cuadrilla'), ('validada', 'Validada por Territorial'), ('rechazada', 'Rechazada por Territorial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('creada', 'Creada por Territorial'), ('derivada', 'Derivada a Departamento'), ('asignada', 'Asignada a Cuadrilla'), ('en_proceso', 'En Proceso por Cuadrilla'), ('finalizada', 'Finalizada por Cuadrilla'), ('validada', 'Validada por Territorial'), ('rechazada', 'Rechazada por Territorial')], default='abierta', max_length=20),
        ),
    ]
