# Generated by Django 5.2.4 on 2025-11-06 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Encuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo_encuesta",
                    models.CharField(
                        max_length=200, verbose_name="Título o nombre encuesta"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripción del incidente"),
                ),
                (
                    "ubicacion",
                    models.CharField(max_length=255, verbose_name="Ubicación"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="encuestas/imagenes/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="encuestas/videos/",
                        verbose_name="Video",
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="encuestas/audios/",
                        verbose_name="Audio",
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("normal", "Normal"),
                            ("baja", "Baja"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "nombre_vecino",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nombre del Vecino",
                    ),
                ),
                (
                    "celular_vecino",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Celular del Vecino",
                    ),
                ),
                (
                    "email_vecino",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email del Vecino",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("derivada", "Derivada"),
                            ("rechazada", "Rechazada"),
                            ("finalizada", "Finalizada"),
                        ],
                        default="abierta",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encuestas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo_incidencia",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gestion.tipoincidencia",
                        verbose_name="Tipo de Incidencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encuesta (Solicitud)",
                "verbose_name_plural": "Encuestas (Solicitudes)",
                "ordering": ["-created"],
            },
        ),
    ]
