# Generated by Django 5.2.4 on 2025-11-01 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_solicitud_fecha_asignacion_cuadrilla_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_asignacion_cuadrilla',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='prioridad_directa',
            field=models.CharField(choices=[('alta', 'Alta'), ('normal', 'Normal'), ('baja', 'Baja')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('creada', 'Creada por Territorial'), ('derivada', 'Derivada a Departamento'), ('asignada', 'Asignada a Cuadrilla'), ('en_proceso', 'En Proceso por Cuadrilla'), ('finalizada', 'Finalizada por Cuadrilla'), ('validada', 'Validada por Territorial'), ('rechazada', 'Rechazada por Territorial')], default='creada', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='territorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_territorial', to=settings.AUTH_USER_MODEL),
        ),
    ]
