# Generated by Django 5.2.4 on 2025-11-01 16:52

from django.db import migrations

def cleanup_solicitud(apps, schema_editor):
    Solicitud = apps.get_model('gestion', 'Solicitud')

    if Solicitud.objects.filter(territorial__isnull=True).exists():
        print("Eliminando solicitudes sin territorial asignado...")
        Solicitud.objects.filter(territorial__isnull=True).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('gestion', '0003_solicitud_fecha_asignacion_cuadrilla_and_more'),
    ]

    operations = [
        migrations.RunPython(cleanup_solicitud),
    ]
