# Generated by Django 5.2.4 on 2025-11-01 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_cleanup_solicitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='usuario_creador',
        ),
        migrations.AlterField(
            model_name='seguimientosolicitud',
            name='estado_anterior',
            field=models.CharField(choices=[('creada', 'Creada por Territorial'), ('derivada', 'Derivada a Departamento'), ('en_proceso', 'En Proceso por Cuadrilla'), ('finalizada', 'Finalizada por Cuadrilla'), ('validada', 'Validada por Territorial'), ('rechazada', 'Rechazada por Territorial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='seguimientosolicitud',
            name='estado_nuevo',
            field=models.CharField(choices=[('creada', 'Creada por Territorial'), ('derivada', 'Derivada a Departamento'), ('en_proceso', 'En Proceso por Cuadrilla'), ('finalizada', 'Finalizada por Cuadrilla'), ('validada', 'Validada por Territorial'), ('rechazada', 'Rechazada por Territorial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('creada', 'Creada por Territorial'), ('derivada', 'Derivada a Departamento'), ('en_proceso', 'En Proceso por Cuadrilla'), ('finalizada', 'Finalizada por Cuadrilla'), ('validada', 'Validada por Territorial'), ('rechazada', 'Rechazada por Territorial')], default='creada', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='territorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
