# Generated by Django 5.2.7 on 2025-11-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("direccion", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="direccion",
            old_name="nombre",
            new_name="nombre_direccion",
        ),
        migrations.RenameField(
            model_name="direccion",
            old_name="encargado",
            new_name="nombre_encargado",
        ),
        migrations.AlterField(
            model_name="direccion",
            name="estado",
            field=models.CharField(default="Activo", max_length=20),
        ),
    ]
