# Generated by Django 5.2.7 on 2025-11-06 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SECPLA", "0002_recuperacionintento"),
        ("direccion", "0002_rename_nombre_direccion_nombre_direccion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="direccion_asociada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios_direccion",
                to="direccion.direccion",
            ),
        ),
    ]
