# Generated by Django 5.2.4 on 2025-10-03 02:16

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('departamento_id', models.BigAutoField(db_column='Departamento_ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('cuadrilla_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('usuario', models.IntegerField(db_column='Usuario_id')),
                ('departamento', models.ForeignKey(db_column='Departamento_id', on_delete=django.db.models.deletion.PROTECT, related_name='Cuadrilla', to='orgs.departamento')),
            ],
            options={
                'verbose_name': 'Cuadrilla',
                'verbose_name_plural': 'Cuadrillas',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('direccion_id', models.AutoField(db_column='Direccion_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='Usuario_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='direccion',
            field=models.ForeignKey(db_column='Direccion_id', on_delete=django.db.models.deletion.PROTECT, related_name='Departamento', to='orgs.direccion'),
        ),
        migrations.CreateModel(
            name='Territorial',
            fields=[
                ('territorial_id', models.BigAutoField(db_column='Territorial_ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('usuario', models.ForeignKey(db_column='Usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='Territorial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Territorial',
                'verbose_name_plural': 'Territoriales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(fields=('direccion', 'nombre'), name='unique_departamento_por_direccion'),
        ),
    ]
