# Generated by Django 5.2.4 on 2025-10-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_alter_direccion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadrilla',
            name='usuario',
            field=models.IntegerField(blank=True, db_column='Usuario_id', null=True),
        ),
    ]
