# Generated by Django 5.2.4 on 2025-10-16 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_departamento_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secpla',
            fields=[
                ('secpla_id', models.BigAutoField(db_column='Secpla_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('usuario', models.ForeignKey(db_column='Usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='Secpla', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secpla',
                'verbose_name_plural': 'Secplas',
                'ordering': ['nombre'],
            },
        ),
    ]
