# Generated by Django 5.2.4 on 2025-10-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_alter_departamento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadrilla',
            name='estado',
            field=models.BooleanField(db_column='Estado', default=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='estado',
            field=models.BooleanField(db_column='Estado', default=True),
        ),
    ]
