# Generated by Django 5.2.4 on 2025-10-27 02:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_alter_cuadrilla_estado_alter_direccion_estado'),
        ('registration', '0003_profile_role_object_id_profile_role_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuadrilla',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='profile',
        ),
        migrations.CreateModel(
            name='CuadrillaMembership',
            fields=[
                ('cuadrilla_membership_id', models.BigAutoField(db_column='Cuadrilla_Membership_ID', primary_key=True, serialize=False)),
                ('desde', models.DateField(db_column='Desde', default=django.utils.timezone.now)),
                ('cuadrilla', models.ForeignKey(db_column='Cuadrilla_id', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='orgs.cuadrilla')),
                ('usuario_id', models.ForeignKey(db_column='Usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='cuadrilla_memberships', to='registration.profile')),
            ],
            options={
                'verbose_name': 'Cuadrilla Membership',
                'verbose_name_plural': 'Cuadrilla Memberships',
            },
        ),
        migrations.CreateModel(
            name='DepartamentoMembership',
            fields=[
                ('departamento_membership_id', models.BigAutoField(db_column='Departamento_Membership_ID', primary_key=True, serialize=False)),
                ('es_encargado', models.BooleanField(db_column='Es_Encargado', default=False)),
                ('desde', models.DateField(db_column='Desde', default=django.utils.timezone.now)),
                ('departamento', models.ForeignKey(db_column='Departamento_id', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='orgs.departamento')),
                ('usuario_id', models.ForeignKey(db_column='Usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='departamento_memberships', to='registration.profile')),
            ],
            options={
                'verbose_name': 'Departamento Membership',
                'verbose_name_plural': 'Departamento Memberships',
            },
        ),
        migrations.CreateModel(
            name='DireccionMembership',
            fields=[
                ('direccion_membership_id', models.BigAutoField(db_column='Direccion_Membership_ID', primary_key=True, serialize=False)),
                ('es_encargado', models.BooleanField(db_column='Es_Encargado', default=False)),
                ('desde', models.DateField(db_column='Desde', default=django.utils.timezone.now)),
                ('direccion', models.ForeignKey(db_column='Direccion_id', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='orgs.direccion')),
                ('usuario_id', models.ForeignKey(db_column='Usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='direccion_memberships', to='registration.profile')),
            ],
            options={
                'verbose_name': 'Dirección Membership',
                'verbose_name_plural': 'Dirección Memberships',
            },
        ),
    ]
