# Generated by Django 5.2.7 on 2025-11-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SECPLA", "0003_usuario_direccion_asociada"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="direccion_asociada",
        ),
    ]
