# Generated by Django 5.2.7 on 2025-11-05 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encuesta", "0003_alter_encuesta_prioridad_and_more"),
        ("pregunta", "__first__"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encuesta",
            name="pregunta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pregunta.pregunta"
            ),
        ),
    ]
