# Generated by Django 5.2.7 on 2025-11-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encuesta", "0004_alter_encuesta_pregunta"),
    ]

    operations = [
        migrations.AddField(
            model_name="encuesta",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("Creada", "Creada"),
                    ("Vigente", "Vigente"),
                    ("Bloqueada", "Bloqueada"),
                ],
                default="Creada",
                max_length=20,
            ),
        ),
    ]
