# Generated by Django 5.2.7 on 2025-11-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidencia", "0003_incidencia_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidencia",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Creada", "Creada"),
                    ("Derivada", "Derivada"),
                    ("Rechazada", "Rechazada"),
                    ("Finalizada", "Finalizada"),
                ],
                default="Activo",
                max_length=20,
            ),
        ),
    ]
