# Generated by Django 5.2.7 on 2025-11-05 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SECPLA", "0002_recuperacionintento"),
        ("incidencia", "0004_alter_incidencia_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidencia",
            name="territorial_creador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidencias_territorial",
                to="SECPLA.usuario",
            ),
        ),
        migrations.AlterField(
            model_name="incidencia",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Abierta", "Abierta"),
                    ("Derivada", "Derivada"),
                    ("Rechazada", "Rechazada"),
                    ("En proceso", "En proceso"),
                    ("Finalizada", "Finalizada"),
                    ("Cerrada", "Cerrada"),
                ],
                default="Abierta",
                max_length=20,
            ),
        ),
    ]
