# Generated by Django 5.2.4 on 2025-11-08 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SECPLA', '0004_remove_usuario_direccion_asociada'),
        ('incidencia', '0005_incidencia_territorial_creador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='cuadrilla_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to='SECPLA.usuario'),
        ),
    ]
