# Generated by Django 5.2.7 on 2025-11-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encuesta", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encuesta",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to="encuestas/audios/"
            ),
        ),
        migrations.AlterField(
            model_name="encuesta",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="encuestas/imagenes/"
            ),
        ),
        migrations.AlterField(
            model_name="encuesta",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="encuestas/videos/"
            ),
        ),
    ]
